menu:
    Blog: /
    Blog2: https://f00bar.cn
    Archive: /archives/
    GitHub: https://github.com/LanceZhu
    Rss: /atom.xml

favicon: /favicon.png
logo: /favicon.png

# Comment
# e.g disqus: seansun
disqus:
duoshuo:

# Analytics
# google-analytics:
# ga: UA-xxxxxxxx-x

# Copyright Infomation
startyear: 2015
